	org #0000

story_block1:
    db "FOR MANY CENTURIES, THE WORLD   "
    db "HAD BEEN AT PEACE. LANDS WERE   "
    db "PROSPEROUS, AND PEOPLE REACHED  "
    db "OLD AGE.                        "
    db "                                "
    db "BUT ALL OF THAT WAS ABOUT TO    "
    db "CHANGE...                       "
story_block2:
    db "SUDDENLY, TOWNS WERE ATTACKED BY"
    db "BEASTS, KILLING PEASANTS. SHIPS "
    db "STARTED SINKING INTO THE OCEAN, "
    db "AND VIOLENT STORMS RUINED CROPS."
    db "                                "
    db "PEOPLE STARTED TO THINK THEY HAD"
    db "LOST THE FAVOR OF THE GODS...   "
story_block3:
    db "BUT ONE NIGHT, THANATOS, GOD OF "
    db "PEACEFUL DEATH, APPEARED IN THE "
    db "DREAMS OF POPOLON.              "
    db "                                "
    db "POPOLON, I AM THANATOS!         "
    db "THE GODS OF OLYMPUS NEED YOUR   "
    db "HELP!                           "
story_block4:
    db "AN EVIL FORTRESS HAS BEEN BUILT "
    db "IN OLYMPUS AGAINST OUR WILL..   "
    db "SOMEONE IS CAUSING PEOPLE TO DIE"
    db "AND THEIR SOULS ARE BEING SENT  "
    db "TO THE FORTRESS, PREVENTING THEM"
    db "FROM REACHING HADES!            "
    db "                                "
    db "YOU ARE OUR ONLY HOPE, ONLY MOR-"
    db "TALS ARE ALLOWED INSIDE. PLEASE "
    db "STOP THE SOURCE OF EVIL!        "
